name: 'Release'

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
      - '.vscode'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Build extension
        shell: bash
        run: |
          node scripts/build.mjs
          npx vite build web

      - name: Install maa.node
        shell: bash
        run: |
          npm i -g yarn
          cd release
          ver=`npm pkg get devDependencies.@nekosu/maa-node`
          for os in win32, linux, darwin; do
            for cpu in x64, arm64; do
              yarn add @nekosu/maa-node-${os}-${cpu}@${ver} --ignore-platform
            done
          done
      
      - name: Package extension
        shell: bash
        run: |
          npm i -g @vscode/vsce
          cd release
          vsce package
          mkdir vsix
          cp *.vsix vsix/

      - uses: actions/upload-artifact@v4
        with:
          name: maa-support-extension
          path: 'release/vsix'

  prepare_package:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: assets
