name: 'Release MaaNode'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'maa/.maaver'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  release:
    if: github.repository == 'neko-para/maa-support-extension'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install And Publish
        shell: bash
        run: |
          npm i -g @vscode/vsce
          cd maa
          scripts/install.sh
          vsce package
          vsce publish -p ${{ secrets.VSCE_TOKEN }} --packagePath *.vsix
